version: "6"
agent:
  command: 'codex exec --dangerously-bypass-approvals-and-sandbox "Read the file {prompt_file} and follow its instructions."'

repositories:
  test-propagation-backend:
    url: git@github.com:MenschMachine/test-propagation-backend.git
  test-propagation-frontend:
    url: git@github.com:MenschMachine/test-propagation-frontend.git

context_sources:
  pwd:
    command: pwd
  commit_message:
    command: gommit -A -n -I
  date:
    command: date

signals:
  run:
    payload: {}

executions:
  test-backend:
    repository: test-propagation-backend
    signals: [run]
    sub_tasks:
      - id: plan
        #prompt: ./prompts/test/plan-backend.md
        before:
          - echo planning...
          - propagate context set :date "$(date -u)" --local
          - propagate context dump
      - id: implementation
        prompt: ./prompts/test/do-nothing.md
        before:
          - echo implementing...
          - propagate context dump
  test-frontend:
    repository: test-propagation-frontend
    sub_tasks:
      - id: noop
        before:
          - propagate context dump

propagation:
  triggers:
    - after: test-backend
      run: test-frontend