version: "6"
agent:
  command: 'codex exec --dangerously-bypass-approvals-and-sandbox "Read the file {prompt_file} and follow its instructions."'

repositories:
  test-propagation-backend:
    url: git@github.com:MenschMachine/test-propagation-backend.git
  test-propagation-frontend:
    url: git@github.com:MenschMachine/test-propagation-frontend.git

context_sources:
  pwd:
    command: pwd
  commit_message:
    command: gommit -A -n -I
  date:
    command: date

signals:
  include:
    - signals/default.yaml
    - signals/github-signals.yaml

executions:
  test-backend:
    repository: test-propagation-backend
    signals: [ start ]
    sub_tasks:
      - id: plan
        before:
          - echo planning...
          - propagate context set :date "$(date -u)" --local
          - propagate context dump
      - id: implementation
        prompt: ./prompts/test/do-nothing.md
        before:
          - echo implementing...
          - propagate context dump
  test-frontend:
    repository: test-propagation-frontend
    sub_tasks:
      - id: noop
        before:
          - propagate context dump
          - echo hi

propagation:
  triggers:
    - after: test-backend
      run: test-frontend
      on_signal: pull_request.labeled
      when:
        label: "bug"
        pr_number: 4
        repository: MenschMachine/test-propagation-frontend