start:
  payload:
    instructions:
      type: string
      required: true
    sender:
      type: string
      required: false

enrich:
  payload:
    instructions:
      type: string
      required: false